// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: internal/service/grpc/pb/airtraffic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFlightsRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *GetFlightsRq) Reset() {
	*x = GetFlightsRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_grpc_pb_airtraffic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlightsRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightsRq) ProtoMessage() {}

func (x *GetFlightsRq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_grpc_pb_airtraffic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightsRq.ProtoReflect.Descriptor instead.
func (*GetFlightsRq) Descriptor() ([]byte, []int) {
	return file_internal_service_grpc_pb_airtraffic_proto_rawDescGZIP(), []int{0}
}

func (x *GetFlightsRq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetFlightsRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flights []*Flight `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"`
}

func (x *GetFlightsRs) Reset() {
	*x = GetFlightsRs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_grpc_pb_airtraffic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlightsRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightsRs) ProtoMessage() {}

func (x *GetFlightsRs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_grpc_pb_airtraffic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightsRs.ProtoReflect.Descriptor instead.
func (*GetFlightsRs) Descriptor() ([]byte, []int) {
	return file_internal_service_grpc_pb_airtraffic_proto_rawDescGZIP(), []int{1}
}

func (x *GetFlightsRs) GetFlights() []*Flight {
	if x != nil {
		return x.Flights
	}
	return nil
}

type Flight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ScheduledDeparture string `protobuf:"bytes,2,opt,name=scheduled_departure,json=scheduledDeparture,proto3" json:"scheduled_departure,omitempty"`
	ScheduledArrival   string `protobuf:"bytes,3,opt,name=scheduled_arrival,json=scheduledArrival,proto3" json:"scheduled_arrival,omitempty"`
	// string departure_airport = 4;
	// string arrival_airport = 5;
	Status          string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AircraftCode    string `protobuf:"bytes,7,opt,name=aircraft_code,json=aircraftCode,proto3" json:"aircraft_code,omitempty"`
	ActualDeparture string `protobuf:"bytes,8,opt,name=actual_departure,json=actualDeparture,proto3" json:"actual_departure,omitempty"`
}

func (x *Flight) Reset() {
	*x = Flight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_grpc_pb_airtraffic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flight) ProtoMessage() {}

func (x *Flight) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_grpc_pb_airtraffic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flight.ProtoReflect.Descriptor instead.
func (*Flight) Descriptor() ([]byte, []int) {
	return file_internal_service_grpc_pb_airtraffic_proto_rawDescGZIP(), []int{2}
}

func (x *Flight) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Flight) GetScheduledDeparture() string {
	if x != nil {
		return x.ScheduledDeparture
	}
	return ""
}

func (x *Flight) GetScheduledArrival() string {
	if x != nil {
		return x.ScheduledArrival
	}
	return ""
}

func (x *Flight) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Flight) GetAircraftCode() string {
	if x != nil {
		return x.AircraftCode
	}
	return ""
}

func (x *Flight) GetActualDeparture() string {
	if x != nil {
		return x.ActualDeparture
	}
	return ""
}

var File_internal_service_grpc_pb_airtraffic_proto protoreflect.FileDescriptor

var file_internal_service_grpc_pb_airtraffic_proto_rawDesc = []byte{
	0x0a, 0x29, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x69, 0x72, 0x74, 0x72,
	0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x69, 0x72,
	0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x22, 0x22, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x3c, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x73, 0x12, 0x2c, 0x0a, 0x07, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61,
	0x69, 0x72, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0xde, 0x01, 0x0a, 0x06, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x13, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x64, 0x5f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x12, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x64, 0x5f, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x41, 0x72, 0x72, 0x69, 0x76,
	0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x69,
	0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x61, 0x69, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x29, 0x0a, 0x10, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x74, 0x75, 0x61,
	0x6c, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x32, 0x57, 0x0a, 0x11, 0x41, 0x69,
	0x72, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x42, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x18, 0x2e,
	0x61, 0x69, 0x72, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x71, 0x1a, 0x18, 0x2e, 0x61, 0x69, 0x72, 0x74, 0x72, 0x61,
	0x66, 0x66, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52,
	0x73, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_service_grpc_pb_airtraffic_proto_rawDescOnce sync.Once
	file_internal_service_grpc_pb_airtraffic_proto_rawDescData = file_internal_service_grpc_pb_airtraffic_proto_rawDesc
)

func file_internal_service_grpc_pb_airtraffic_proto_rawDescGZIP() []byte {
	file_internal_service_grpc_pb_airtraffic_proto_rawDescOnce.Do(func() {
		file_internal_service_grpc_pb_airtraffic_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_service_grpc_pb_airtraffic_proto_rawDescData)
	})
	return file_internal_service_grpc_pb_airtraffic_proto_rawDescData
}

var file_internal_service_grpc_pb_airtraffic_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_service_grpc_pb_airtraffic_proto_goTypes = []interface{}{
	(*GetFlightsRq)(nil), // 0: airtraffic.GetFlightsRq
	(*GetFlightsRs)(nil), // 1: airtraffic.GetFlightsRs
	(*Flight)(nil),       // 2: airtraffic.Flight
}
var file_internal_service_grpc_pb_airtraffic_proto_depIdxs = []int32{
	2, // 0: airtraffic.GetFlightsRs.flights:type_name -> airtraffic.Flight
	0, // 1: airtraffic.AirTrafficService.GetFlights:input_type -> airtraffic.GetFlightsRq
	1, // 2: airtraffic.AirTrafficService.GetFlights:output_type -> airtraffic.GetFlightsRs
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_service_grpc_pb_airtraffic_proto_init() }
func file_internal_service_grpc_pb_airtraffic_proto_init() {
	if File_internal_service_grpc_pb_airtraffic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_service_grpc_pb_airtraffic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlightsRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_grpc_pb_airtraffic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlightsRs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_grpc_pb_airtraffic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_service_grpc_pb_airtraffic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_grpc_pb_airtraffic_proto_goTypes,
		DependencyIndexes: file_internal_service_grpc_pb_airtraffic_proto_depIdxs,
		MessageInfos:      file_internal_service_grpc_pb_airtraffic_proto_msgTypes,
	}.Build()
	File_internal_service_grpc_pb_airtraffic_proto = out.File
	file_internal_service_grpc_pb_airtraffic_proto_rawDesc = nil
	file_internal_service_grpc_pb_airtraffic_proto_goTypes = nil
	file_internal_service_grpc_pb_airtraffic_proto_depIdxs = nil
}
